<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="OpenText Functional Testing" productVer="24.4" os="Windows 11" host="LENOVO-L14-GEN-"><DocLocation><![CDATA[D:\UFT Project\Web\Tests\E2E_Shopping]]></DocLocation></General>
<Doc rID="T1"   productName= "OpenText Functional Testing"  >
<DName><![CDATA[E2E_Shopping]]></DName>
<Res><![CDATA[Res22]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action_Shopping]]></AName>
<Action rID="T5">
<AName><![CDATA[Action_Login [Login]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[11-01-2025 - 18:51:39]]></Time>
<TimeTick>1736601699</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[11-01-2025 - 18:51:39]]></Time>
<TimeTick>1736601699</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Action_Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Action_Login [Login]" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[11-01-2025 - 18:51:59]]></Time>
<TimeTick>1736601719</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop.Maximize]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-01-2025 - 18:51:59]]></Time>
<TimeTick>1736601719</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Action_Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop.Maximize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop - Landing Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:00]]></Time>
<TimeTick>1736601720</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Log in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:00]]></Time>
<TimeTick>1736601720</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="18" Source="Action_Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Log in.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="17" Source="Action_Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop - Landing Page]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:02]]></Time>
<TimeTick>1736601722</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["rakesh_demo1@gmail.com"]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:02]]></Time>
<TimeTick>1736601722</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="21" Source="Action_Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Ramos@12345"]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:02]]></Time>
<TimeTick>1736601722</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="23" Source="Action_Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Log in.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:02]]></Time>
<TimeTick>1736601722</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="25" Source="Action_Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Log in.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="20" Source="Action_Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop. Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop - Landing Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:24]]></Time>
<TimeTick>1736601744</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Logged_Email.GetROProperty "innertext"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:24]]></Time>
<TimeTick>1736601744</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="69" status="Warning" >
<Disp><![CDATA[Logged_Email.GetROProperty "innertext"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Logged_Email]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Logged_Email"&nbsp;(of&nbsp;class&nbsp;Link).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:24]]></Time>
<TimeTick>1736601744</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Logged_Email]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>miccommentproperty = <br>Mercury Class = Link<br>Html Tag = A<br>_xpath = //DIV[4]/DIV[1]/DIV[1]/DIV[2]/DIV[1]/UL[1]/LI[1]/A[1]<br>|Visible = -1<br>Text = *@gmail.com<br>Name = rakesh_demo@gmail.com<br>Html Id = <br>Href = https://demowebshop.tricentis.com/customer/info<br>DHTML Class = account<br>acc_name = <br>]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:24]]></Time>
<TimeTick>1736601744</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="71" status="Warning" nType="Description" >
<Disp><![CDATA[Logged_Email]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="70" status="Failed" nType="Run Error" >
<Disp><![CDATA[Logged_Email]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="68" status="Failed" >
<Disp><![CDATA[Demo Web Shop - Landing Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" status="Failed" Source="Action_Login [Login]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:24]]></Time>
<TimeTick>1736601744</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop - Landing Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:24]]></Time>
<TimeTick>1736601744</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Logged_Email&quot; (of class Link).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Function file: D:\UFT Project\Web\Functions\UtilityFunctions.qfl<BR/>Line (3): &quot;	strText = Obj.GetROProperty(&quot;innertext&quot;)&quot;.]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:24]]></Time>
<TimeTick>1736601744</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="74" status="Failed" Source="D:\UFT Project\Web\Functions\UtilityFunctions.qfl" SourceLine="2" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="73" status="Failed" Source="D:\UFT Project\Web\Functions\UtilityFunctions.qfl" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop - Landing Page]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="72" status="Failed" Source="D:\UFT Project\Web\Functions\UtilityFunctions.qfl" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[1382256]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[ Unable to Login with  rakesh_demo1@gmail.com Please check the credentials]]></Obj>
<Details ><![CDATA[ Unable to Login with  rakesh_demo1@gmail.com Please check the credentials]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:24]]></Time>
<TimeTick>1736601744</TimeTick>
<NodeArgs eType="User" icon="13" nRep="75" status="Failed" Source="D:\UFT Project\Web\Functions\UtilityFunctions.qfl" SourceLine="-1" >
<Disp><![CDATA[ Unable to Login with  rakesh_demo1@gmail.com Please check the credentials]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11-01-2025 - 18:51:36" eTime="11-01-2025 - 18:52:24" passed="1" failed="3" warnings="2" ><Param paramInOut = "In"><ParamName><![CDATA[Email]]></ParamName><ParamVal><![CDATA[rakesh_demo1@gmail.com]]></ParamVal>
</Param>
<Param paramInOut = "In"><ParamName><![CDATA[Password]]></ParamName><ParamVal><![CDATA[Ramos@12345]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Failed" >
<Disp><![CDATA[Action_Login [Login] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T24">
<AName><![CDATA[ShoppingProducts [SelectProducts]]]></AName>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:46]]></Time>
<TimeTick>1736601766</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop - Shopping Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:46]]></Time>
<TimeTick>1736601766</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Apparel & Shoes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:46]]></Time>
<TimeTick>1736601766</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="81" Source="ShoppingProducts [SelectProducts]" SourceLine="-1" >
<Disp><![CDATA[Apparel & Shoes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[AIUtil.SetContext]]></Obj>
<Details plainTxt="False" ><![CDATA[Set context Browser("[ Demo Web Shop. Apparel & Shoes ]") for AIUtil]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:54]]></Time>
<TimeTick>1736601774</TimeTick>
<NodeArgs eType="Replay" icon="0" nRep="82" nType="AIUtil" Source="ShoppingProducts [SelectProducts]" SourceLine="-1" >
<Disp><![CDATA[AIUtil.SetContext]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 3).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:55]]></Time>
<TimeTick>1736601775</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="84" Source="ShoppingProducts [SelectProducts]" SourceLine="-1" >
<Disp><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 3).Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 4).Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-01-2025 - 18:52:58]]></Time>
<TimeTick>1736601778</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="86" Source="ShoppingProducts [SelectProducts]" SourceLine="-1" >
<Disp><![CDATA[AIUtil.FindTextBlock("Add to cart", micFromLeft, 4).Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="80" Source="ShoppingProducts [SelectProducts]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop - Shopping Page]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="79" Source="ShoppingProducts [SelectProducts]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11-01-2025 - 18:52:24" eTime="11-01-2025 - 18:52:58" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="77" >
<Disp><![CDATA[ShoppingProducts [SelectProducts] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T31">
<AName><![CDATA[Action_ShoppingCart [ShoppingCart]]]></AName>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ shopping cart ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:20]]></Time>
<TimeTick>1736601800</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="90" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[[ shopping cart ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop- Shopping Cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[ProductTable.RowCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="94" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[ProductTable.RowCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="General" icon="15" nRep="96" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="General" icon="15" nRep="97" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="General" icon="15" nRep="98" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="93" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop- Shopping Cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="92" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[Blue Jeans]]></Obj>
<Details ><![CDATA[Blue Jeans is selected and is displayed in the Cart]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="User" icon="13" nRep="99" status="Passed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[Blue Jeans]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop- Shopping Cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[RowCount]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="General" icon="15" nRep="102" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="General" icon="15" nRep="103" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA["ProductTable":Function Call]]></Obj>
<Details plainTxt="False" ><![CDATA[CellText]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="General" icon="15" nRep="104" >
<Disp><![CDATA["ProductTable":Function Call]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="101" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop- Shopping Cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="100" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[Casual Golf Belt]]></Obj>
<Details ><![CDATA[Casual Golf Belt is selected and is displayed in the Cart]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="User" icon="13" nRep="105" status="Passed" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[Casual Golf Belt]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop- Shopping Cart]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Sub-Total:.GetCellData]]></Obj>
<Details plainTxt="False" ><![CDATA[1, 2]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="109" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[Sub-Total:.GetCellData]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[termsofservice.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="111" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[termsofservice.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Checkout.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:22]]></Time>
<TimeTick>1736601802</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="113" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[Checkout.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="108" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop- Shopping Cart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="107" Source="Action_ShoppingCart [ShoppingCart]" SourceLine="-1" >
<Disp><![CDATA[Demo Web Shop]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11-01-2025 - 18:52:58" eTime="11-01-2025 - 18:53:22" passed="2" failed="0" warnings="0" ><Param paramInOut = "In"><ParamName><![CDATA[Products]]></ParamName><ParamVal><![CDATA[Blue Jeans|Casual Golf Belt]]></ParamVal>
</Param>
<Param paramInOut = "Out"><ParamName><![CDATA[SubTotal_out]]></ParamName><ParamVal><![CDATA[2.00]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="5" nRep="88" status="Passed" >
<Disp><![CDATA[Action_ShoppingCart [ShoppingCart] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T51">
<AName><![CDATA[Action_Checkout_BillingAddress [Checkout_BillingAddress]]]></AName>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:42]]></Time>
<TimeTick>1736601822</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Demo Web Shop. Checkout]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:42]]></Time>
<TimeTick>1736601822</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.FirstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Dhanya"]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:42]]></Time>
<TimeTick>1736601822</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="119" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="-1" >
<Disp><![CDATA[BillingNewAddress.FirstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.LastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Rakesh"]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:42]]></Time>
<TimeTick>1736601822</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="121" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="-1" >
<Disp><![CDATA[BillingNewAddress.LastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Address1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["DD SilverStone"]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:42]]></Time>
<TimeTick>1736601822</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="123" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="-1" >
<Disp><![CDATA[BillingNewAddress.Address1.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Address2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Vaduthala"]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:42]]></Time>
<TimeTick>1736601822</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="125" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="-1" >
<Disp><![CDATA[BillingNewAddress.Address2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.City.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Kochi"]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:42]]></Time>
<TimeTick>1736601822</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="127" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="-1" >
<Disp><![CDATA[BillingNewAddress.City.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Company.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["IGS"]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:43]]></Time>
<TimeTick>1736601823</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="129" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="-1" >
<Disp><![CDATA[BillingNewAddress.Company.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.Email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Test@igs.com"]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:43]]></Time>
<TimeTick>1736601823</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="131" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="-1" >
<Disp><![CDATA[BillingNewAddress.Email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.FaxNumber.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7637677322"]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:43]]></Time>
<TimeTick>1736601823</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="133" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="-1" >
<Disp><![CDATA[BillingNewAddress.FaxNumber.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[BillingNewAddress.PhoneNumber.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7766368999"]]></Details>
<Time><![CDATA[11-01-2025 - 18:53:43]]></Time>
<TimeTick>1736601823</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="135" Source="Action_Checkout_BillingAddress [Checkout_BillingAddress]" SourceLine="-1" >